<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Categorias' => '',
    'Comercios' => '',
    'Create' => 'Crear',
    'Create Categoria' => 'Crear Categoria',
    'Create Comercio' => 'Crear Comercio',
    'Create Producto' => 'Crear Producto',
    'Delete' => 'Eliminar',
    'Domingo' => '',
    'Horario Desde' => '',
    'Horario Hasta' => '',
    'ID' => 'Identificador',
    'Id Categoria' => 'Identificador Categoria',
    'Imagen' => '',
    'Jueves' => '',
    'Lunes' => '',
    'Martes' => '',
    'Miercoles' => '',
    'Nombre' => '',
    'Prioridad' => '',
    'Productos' => '',
    'Reset' => 'Reiniciar',
    'Sabado' => '',
    'Search' => 'Buscar',
    'Ubicacion' => '',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actulizar modelo',
    'Viernes' => '',
];
